### ISSUE TITLE
Question about worker  page postMessage protocol

### ISSUE THREAD

**Issue by mmzeeman** [cotonic/cotonic#1]
@mworrell The postMessage api is asynchronous as well, so you don't get responses directly.

We should probably add some mqtt protocol features like a connect (probably with keep-alive timer from mqtt-sn)/connack/disconnect messages with a will. That way the workers can find out if the page responds. 

We probably also need pingreq and pingresp messages from mqtt-sn because there is no way for a worker or the page to find out if the worker is still running.

**Comment by mworrell** [comment]
Whilst adding the socket code, I realized that the message format should ideally be the same as the fields we use for the MQTT encoding. This prevents that we need to any translations.

The messages can be seen in the test code:

https://github.com/cotonic/cotonic/blob/master/test/cotonic.mqtt_packet.test.js
