### ISSUE TITLE
Fix things so cotonic works on IE11

### ISSUE THREAD

**Issue by mmzeeman** [cotonic/cotonic#24]
There are a couple of changes needed to make cotonic work on IE11. (Run tests with browserstack)

  - no startsWith available.
  - no codePointAt available.

Maybe other things need to be added to the polyfills.

Or @mworrell, should we remove the polyfills from the base cotonic script and tell people to load it separately when needed (somebody uses IE11)? We could check if the required features exist, when they do not, inject a script with the required polyfills.

**Comment by mmzeeman** [comment]
I was thinking about removing all the polyfill code, and check first if the browser has all the required features (Promise, fetch, codePointAt). If it does, start immediately. If not insert a script tag with a polyfill. When that is loaded, start. The polyfill is needed for IE11 only I think

![20200131131614](https://user-images.githubusercontent.com/1024972/73538681-e2f1c780-442b-11ea-8605-87c02e409fd9.png)

We could even use https://polyfill.io to serve the polyfill itself. When somebody really wants to have a private (not externally downloaded) they could load it before loading cotonic.

**Comment by mmzeeman** [comment]
Busy with polyfill.io, but stumbled into a problem with polyfill.io inside a web-worker.

See: https://github.com/Financial-Times/polyfill-service/issues/2126

**Comment by mworrell** [comment]
I guess we are a bit on the bleeding edge.

As this is (for now) only for IE11, do we know which functions are missing and add them in a different way?

Of course, it is better if polyfill would fix the problem.

**Comment by mmzeeman** [comment]
Yes it looks like not all of the polyfills have been tested with web workers. 

Yes, I removed fetch from the worker polyview. It does not pull in polyfill for Symbol then. On the worker side we only need Promise and String.prototype.startsWith. I can now run the do nothing worker on IE11. I want to be able to run all tests on IE11, so I have to change the tests so that the polyfill is also loaded then.
